CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  firstName VARCHAR(255),
  lastName VARCHAR(255),
  birthDate DATE,
  avatar VARCHAR(255),
  isAdmin BOOLEAN DEFAULT FALSE
);
